version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  node: circleci/node@4.7

workflows:
  upload-to-codecov:
    jobs:
      - node/test:
          version: '18.11'
          pkg-manager: npm
          post-steps:
            - codecov/upload
